// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proiect_MDP.Data;

#nullable disable

namespace proiect_MDP.Migrations
{
    [DbContext(typeof(proiect_MDPContext))]
    [Migration("20240109140306_Companie")]
    partial class Companie
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("proiect_MDP.Models.Companie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Companie");
                });

            modelBuilder.Entity("proiect_MDP.Models.Terminal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("TerminalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Terminal");
                });

            modelBuilder.Entity("proiect_MDP.Models.Zbor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("CompanieID")
                        .HasColumnType("int");

                    b.Property<string>("Destinatie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int?>("TerminalID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ZborDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CompanieID");

                    b.HasIndex("TerminalID");

                    b.ToTable("Zbor");
                });

            modelBuilder.Entity("proiect_MDP.Models.Zbor", b =>
                {
                    b.HasOne("proiect_MDP.Models.Companie", "Companie")
                        .WithMany()
                        .HasForeignKey("CompanieID");

                    b.HasOne("proiect_MDP.Models.Terminal", "Terminal")
                        .WithMany("Zboruri")
                        .HasForeignKey("TerminalID");

                    b.Navigation("Companie");

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("proiect_MDP.Models.Terminal", b =>
                {
                    b.Navigation("Zboruri");
                });
#pragma warning restore 612, 618
        }
    }
}
